name: hack_u_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.0.2
  audioplayers: ^6.1.0
  shared_preferences: ^2.1.0
  toml: ^0.18.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bgm/
    - assets/se/
    - assets/se/moti/
    - assets/se/etoq/
    - assets/se/karuta/
    - assets/title_screen/
    - assets/select_screen/
    - assets/select_screen/titles/
    - assets/select_screen/explain/
    - assets/moti/
    - assets/timer/
    - assets/hagaki/image/
    - assets/hagaki/image/button/
    - assets/hagaki/image/clock/
    - assets/hagaki/image/folder/
    - assets/hagaki/image/hagaki/
    - assets/hagaki/image/haikei/
    - assets/hagaki/sound/
    - assets/hagaki/toml/
    - assets/etoQ/
    - assets/etoQ/animals/
    - assets/karuta/
    - assets/karuta/i/
    - assets/karuta/ro/
    - assets/karuta/ha/
    - assets/escape/
