greetings = [
    "新年あけましておめでとうございます",
    "今年もよろしくお願い申し上げます",
    "素晴らしい一年になりますように",
    "健康と幸せを祈っています",
    "新しい年が素晴らしい年でありますように",
    "明るい未来を一緒に歩みましょう",
    "今年も笑顔あふれる年に",
    "今年もお世話になります",
    "ご多幸をお祈り申し上げます",
    "幸せな一年となりますように",
    "明けましておめでとうございます",
    "健康第一で素晴らしい年を迎えましょう",
    "新しい年もご健勝でありますように",
    "皆様にとって良い年でありますように",
    "希望に満ちた一年をお過ごしください",
    "素敵な一年となりますようお祈りします",
    "新年もよろしくお願いいたします",
    "実り多き一年となりますように",
    "ご多忙の折、どうぞお身体にご自愛ください",
    "昨年はお世話になりました。今年もよろしく"
]
