location = [
    {name="北海道", type=4, capital=["札幌市", "旭川市", "函館市", "帯広市", "釧路市"]},
    {name="青森県", type=1, capital=["青森市", "弘前市", "八戸市", "むつ市", "五所川原市"]},
    {name="岩手県", type=1, capital=["盛岡市", "花巻市", "北上市", "一関市", "奥州市"]},
    {name="宮城県", type=1, capital=["仙台市", "石巻市", "塩竈市", "多賀城市", "名取市"]},
    {name="秋田県", type=1, capital=["秋田市", "横手市", "大館市", "由利本荘市", "能代市"]},
    {name="山形県", type=1, capital=["山形市", "米沢市", "鶴岡市", "酒田市", "天童市"]},
    {name="福島県", type=1, capital=["福島市", "会津若松市", "郡山市", "いわき市", "須賀川市"]},
    {name="茨城県", type=1, capital=["水戸市", "つくば市", "土浦市", "日立市", "鹿嶋市"]},
    {name="栃木県", type=1, capital=["宇都宮市", "小山市", "栃木市", "足利市", "那須塩原市"]},
    {name="群馬県", type=1, capital=["前橋市", "高崎市", "桐生市", "伊勢崎市", "太田市"]},
    {name="東京都", type=1, capital=["新宿区", "港区", "渋谷区", "豊島区", "中央区"]},
    {name="埼玉県", type=1, capital=["さいたま市", "川越市", "熊谷市", "越谷市", "所沢市"]},
    {name="千葉県", type=1, capital=["千葉市", "船橋市", "市川市", "松戸市", "柏市"]},
    {name="神奈川県", type=1, capital=["横浜市", "川崎市", "相模原市", "藤沢市", "小田原市"]},
    {name="新潟県", type=1, capital=["新潟市", "長岡市", "三条市", "上越市", "柏崎市"]},
    {name="富山県", type=1, capital=["富山市", "高岡市", "魚津市", "黒部市", "砺波市"]},
    {name="石川県", type=1, capital=["金沢市", "小松市", "七尾市", "輪島市", "加賀市"]},
    {name="福井県", type=1, capital=["福井市", "敦賀市", "鯖江市", "大野市", "勝山市"]},
    {name="山梨県", type=1, capital=["甲府市", "富士吉田市", "甲斐市", "笛吹市", "都留市"]},
    {name="長野県", type=1, capital=["長野市", "松本市", "上田市", "飯田市", "佐久市"]},
    {name="岐阜県", type=1, capital=["岐阜市", "大垣市", "高山市", "多治見市", "中津川市"]},
    {name="静岡県", type=1, capital=["静岡市", "浜松市", "富士市", "沼津市", "掛川市"]},
    {name="愛知県", type=1, capital=["名古屋市", "豊橋市", "岡崎市", "一宮市", "春日井市"]},
    {name="三重県", type=2, capital=["津市", "四日市市", "鈴鹿市", "松阪市", "伊勢市"]},
    {name="滋賀県", type=2, capital=["大津市", "彦根市", "草津市", "長浜市", "守山市"]},
    {name="京都府", type=2, capital=["京都市", "宇治市", "福知山市", "舞鶴市", "亀岡市"]},
    {name="大阪府", type=2, capital=["大阪市", "堺市", "東大阪市", "吹田市", "豊中市"]},
    {name="兵庫県", type=2, capital=["神戸市", "姫路市", "西宮市", "尼崎市", "明石市"]},
    {name="奈良県", type=2, capital=["奈良市", "橿原市", "生駒市", "大和高田市", "天理市"]},
    {name="和歌山県", type=2, capital=["和歌山市", "田辺市", "橋本市", "海南市", "新宮市"]},
    {name="鳥取県", type=2, capital=["鳥取市", "米子市", "倉吉市", "境港市", "湯梨浜町"]},
    {name="島根県", type=2, capital=["松江市", "出雲市", "浜田市", "益田市", "安来市"]},
    {name="岡山県", type=2, capital=["岡山市", "倉敷市", "津山市", "玉野市", "笠岡市"]},
    {name="広島県", type=2, capital=["広島市", "福山市", "尾道市", "呉市", "三原市"]},
    {name="山口県", type=2, capital=["山口市", "下関市", "宇部市", "岩国市", "防府市"]},
    {name="徳島県", type=2, capital=["徳島市", "鳴門市", "阿南市", "小松島市", "吉野川市"]},
    {name="香川県", type=2, capital=["高松市", "丸亀市", "観音寺市", "三豊市", "さぬき市"]},
    {name="愛媛県", type=2, capital=["松山市", "今治市", "宇和島市", "新居浜市", "大洲市"]},
    {name="高知県", type=2, capital=["高知市", "南国市", "四万十市", "宿毛市", "須崎市"]},
    {name="福岡県", type=3, capital=["福岡市", "北九州市", "久留米市", "飯塚市", "春日市"]},
    {name="佐賀県", type=3, capital=["佐賀市", "唐津市", "鳥栖市", "伊万里市", "武雄市"]},
    {name="長崎県", type=3, capital=["長崎市", "佐世保市", "諫早市", "大村市", "島原市"]},
    {name="熊本県", type=3, capital=["熊本市", "八代市", "人吉市", "玉名市", "阿蘇市"]},
    {name="大分県", type=3, capital=["大分市", "別府市", "中津市", "佐伯市", "臼杵市"]},
    {name="宮崎県", type=3, capital=["宮崎市", "延岡市", "都城市", "日南市", "小林市"]},
    {name="鹿児島県", type=3, capital=["鹿児島市", "霧島市", "薩摩川内市", "鹿屋市", "枕崎市"]},
    {name="沖縄県", type=4, capital=["那覇市", "沖縄市", "浦添市", "宜野湾市", "名護市"]},
    {name="America", type=5, capital=["Washington D.C.", "New York", "Los Angeles", "Chicago", "Houston"]},
    {name="France", type=5, capital=["Paris", "Marseille", "Lyon", "Toulouse", "Nice"]},
    {name="Germany", type=5, capital=["Berlin", "Hamburg", "Munich", "Frankfurt", "Stuttgart"]},
    {name="Australia", type=5, capital=["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"]},
    {name="India", type=5, capital=["New Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata"]},
    {name="エリザビア", type=6, capital=["エリザシティ", "ガーデンタウン", "リバービル", "サンセット市", "ホライズン村"]},
    {name="ルミナス", type=6, capital=["ルミナ市", "シャインタウン", "グレイシティ", "ブルームビレッジ", "オーラポート"]},
    {name="ファンタシア", type=6, capital=["クリスタル市", "ムーンタウン", "スター港", "ネオン村", "フェアリーヒル"]},
    {name="ゼニウム", type=6, capital=["アルファシティ", "ベータ市", "ガンマ町", "デルタ村", "オメガポート"]},
    {name="ネクサス", type=6, capital=["ネクサス市", "ユニタウン", "コスモビル", "オービット港", "グラヴィ村"]},
]